export const dummyUsers = [
    [
        1,
        "Организатор1",
        "123",
        "Фамилия_Организатора_1",
        "org1@gmail.com",
        "organizer"
    ],
    [
        2,
        "Организатор2",
        "123",
        "Фамилия_Организатора_2",
        "org2@gmail.com",
        "organizer"
    ],
    [
        3,
        "Организатор3",
        "123",
        "Фамилия_Организатора_3",
        "org3@gmail.com",
        "organizer"
    ],
    [
        4,
        "Реконструктор1",
        "фывфыв",
        "Фамилия_Реконструктора_1",
        "rec1@gmail.com",
        "reenactor"
    ],
    [
        5,
        "Реконструктор2",
        "фывфыв",
        "Фамилия_Реконструктора_2",
        "rec2@gmail.com",
        "reenactor"
    ],
    [
        6,
        "Реконструктор3",
        "фывфыв",
        "Фамилия_Реконструктора_3",
        "rec3@gmail.com",
        "reenactor"
    ],
    [
        7,
        "Зритель1",
        "фывфыв",
        "Фамилия_Зрителя_1",
        "user1@gmail.com",
        "default_user"
    ],
    [
        8,
        "Зритель2",
        "qwer",
        "Фамилия_Зрителя_2",
        "user2@gmail.com",
        "default_user"
    ],
    [
        9,
        "Зритель3",
        "qwer",
        "Фамилия_Зрителя_3",
        "user3@gmail.com",
        "default_user"
    ],
    [
        10,
        "testName",
        "testSurname",
        "pwd101010100",
        "testemail@gmail.com",
        "default_user"
    ]
]